# Sevendi Eldrige Rifki Poluan🔥🔥🔥
### Descriptions: NLP Fundamental

In [159]:
# working environment
!nvidia-smi

Thu Apr  6 08:00:32 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090         On | 00000000:65:00.0 Off |                  N/A |
| 53%   45C    P2              129W / 390W|  23446MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
!pip install pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 161.9 kB/s eta 0:00:0000:0100:03
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 675.7 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 670.6 kB/s eta 0:00:00a 0:00:01


In [4]:
!pip install scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 172.9 kB/s eta 0:00:0000:0100:02
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 216.8 kB/s eta 0:00:00a 0:00:01


<font color='red'>Import the necessary libraries</font>

In [160]:
import tensorflow as tf
import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import time

In [6]:
tf.__version__

'2.12.0'

<font color='red'>Download the PubMed200kRCT_medical_abstracts dataset, which is a collection of around 200,000 labelled Randomized Controlled Trial (RCT) abstracts, from the paper titled ["PubMed 200k RCT: a Dataset for Sequential Sentence Classification in Medical Abstracts"](https://arxiv.org/abs/1710.06071) published in 2017. For more detailed information about the datasets, please refer to the original paper.</font>

In [29]:
!git clone https://github.com/Franck-Dernoncourt/pubmed-rct.git

Cloning into 'pubmed-rct'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 33 (delta 5), reused 5 (delta 5), pack-reused 25
Unpacking objects: 100% (33/33), done.


In [30]:
!ls pubmed-rct

PubMed_200k_RCT
PubMed_200k_RCT_numbers_replaced_with_at_sign
PubMed_20k_RCT
PubMed_20k_RCT_numbers_replaced_with_at_sign
README.md


In [35]:
!ls pubmed-rct/PubMed_200k_RCT_numbers_replaced_with_at_sign

dev.txt  test.txt  train.zip


In [47]:
!unzip pubmed-rct/PubMed_200k_RCT_numbers_replaced_with_at_sign/train.zip -d pubmed-rct/PubMed_200k_RCT_numbers_replaced_with_at_sign/

Archive:  pubmed-rct/PubMed_200k_RCT_numbers_replaced_with_at_sign/train.zip
  inflating: pubmed-rct/PubMed_200k_RCT_numbers_replaced_with_at_sign/train.txt  


In [48]:
!ls pubmed-rct/PubMed_200k_RCT_numbers_replaced_with_at_sign

dev.txt  test.txt  train.txt  train.zip


<font color='red'>Load the dataset from txt files and read their contents.</font>

In [7]:
train_data = open("pubmed-rct/PubMed_200k_RCT_numbers_replaced_with_at_sign/train.txt", 'r').readlines()
test_data = open("pubmed-rct/PubMed_200k_RCT_numbers_replaced_with_at_sign/test.txt", 'r').readlines()
val_data = open("pubmed-rct/PubMed_200k_RCT_numbers_replaced_with_at_sign/dev.txt", 'r').readlines()

In [52]:
train_data[:3]

['###24491034\n',
 'BACKGROUND\tThe emergence of HIV as a chronic condition means that people living with HIV are required to take more responsibility for the self-management of their condition , including making physical , emotional and social adjustments .\n',
 'BACKGROUND\tThis paper describes the design and evaluation of Positive Outlook , an online program aiming to enhance the self-management skills of gay men living with HIV .\n']

<font color='red'>Dataset Preparation: Separating Input Features and Target</font>

In [174]:
def prepare_data(data):
    all_data = []
    one_abstract = ''
    for line in data:
        if line.startswith("###"):
            pass
        elif line.isspace():
            one_abstract = one_abstract.split("\n") 
            for i, text in enumerate(one_abstract):
                dict_data = {}
                split = text.split("\t")
                if len(split) > 1: 
                    label = split[0]
                    target = '' . join(split[1]).strip()
                    dict_data['target'] = label
                    dict_data['text'] = target
                    dict_data['line_index'] = i + 1
                    dict_data['total_lines'] = len(one_abstract) 
                    
                    all_data.append(dict_data)
                
            one_abstract = '' 
        else:
            one_abstract += line
            
    return all_data 

In [175]:
train_raw = pd.DataFrame(prepare_data(train_data))
test_raw = pd.DataFrame(prepare_data(test_data))
val_raw = pd.DataFrame(prepare_data(val_data))

In [55]:
train_raw.head()

target                                               text  line_index  \
0  BACKGROUND  The emergence of HIV as a chronic condition me...           1   
1  BACKGROUND  This paper describes the design and evaluation...           2   
2     METHODS  This study is designed as a randomised control...           3   
3     METHODS  The intervention group will participate in the...           4   
4     METHODS  The program is based on self-efficacy theory a...           5   

   total_lines  
0           12  
1           12  
2           12  
3           12  
4           12

In [176]:
x_train_raw, y_train_raw = train_raw.text, train_raw.target
x_test_raw, y_test_raw = test_raw.text, test_raw.target
x_val_raw, y_val_raw = val_raw.text, val_raw.target

In [177]:
x_train_raw[0], y_train_raw[0]

('The emergence of HIV as a chronic condition means that people living with HIV are required to take more responsibility for the self-management of their condition , including making physical , emotional and social adjustments .',
 'BACKGROUND')

<font color='red'>Convert the label into integer values for encoding in preparation to be fed into the network.</font>

In [178]:
encoder = LabelEncoder()
encoder.fit(y_train_raw)

LabelEncoder()

In [179]:
y_train_raw_en = encoder.transform(y_train_raw)
y_test_raw_en = encoder.transform(y_test_raw)
y_val_raw_en = encoder.transform(y_val_raw)

In [180]:
y_train_raw_en[:10]

array([0, 0, 2, 2, 2, 2, 2, 2, 2, 1])

<font color='red'>Convert the dataset into a tensor format.</font>

In [212]:
train = tf.data.Dataset.from_tensor_slices((x_train_raw[:1000], y_train_raw_en[:1000]))
test = tf.data.Dataset.from_tensor_slices((x_test_raw, y_test_raw_en))
val = tf.data.Dataset.from_tensor_slices((x_val_raw, y_val_raw_en))

<font color='red'>
    Configure the token count and sequence length for text vectorization and embedding.
</font>
</br>
    
    APPROXIMATE_TOKEN_COUNT: I calculated the approximate token count based on the number of unique tokens in the entire training set.

    SEQ_LENGTH: I determined the sequence length based on the occurrence of tokens in the dataset, where I selected the length that covers approximately 97% of the tokens in the dataset.



In [182]:
APPROXIMATE_TOKEN_COUNT = len(set(' ' . join(x_train_raw).split(' ')))
SEQ_LENGTH = int(np.percentile([len(x) for x in x_train_raw], 97))

In [184]:
APPROXIMATE_TOKEN_COUNT, SEQ_LENGTH

(326178, 314)

<font color='red'>We will set up the vectorization and embedding model to process the input sentences, focusing on **text-level features**.</font>
    
    The dataset adaptation process may take some time due to the large amount of data. To address this, you can consider using transfer learning by extracting pre-trained embeddings from existing models, which can provide better features and save time as well. But, in this case, we will not be using that approach.

In [230]:
vectorize = tf.keras.layers.TextVectorization(max_tokens=APPROXIMATE_TOKEN_COUNT,
                                              output_mode="int",
                                              output_sequence_length=SEQ_LENGTH,
                                              split="whitespace")

In [ ]:
start_time = time.perf_counter()
vectorize.adapt(x_train_raw)
end_time = time.perf_counter()
print(end_time - start_time, 's')

In [187]:
vectorize([x_train_raw[0]])

<tf.Tensor: shape=(1, 314), dtype=int64, numpy=
array([[   2, 3009,    3,  545,   25,    8,  241,  559,  970,   26,  656,
        1234,    7,  545,   67,  408,    6, 2116,   59, 9855,   12,    2,
        2288,    3,  123,  559,  309, 2220,  239, 1528,    4,  642, 4723,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,   

In [188]:
embedding = tf.keras.layers.Embedding(input_dim=APPROXIMATE_TOKEN_COUNT, 
                                      output_dim=256, 
                                      input_length=SEQ_LENGTH)

In [189]:
embedding(vectorize([x_train_raw[0]]))

<tf.Tensor: shape=(1, 314, 256), dtype=float32, numpy=
array([[[ 0.03627015, -0.03426458, -0.02339865, ...,  0.01825185,
          0.01053284,  0.03210547],
        [-0.04784089, -0.00884818, -0.02709348, ...,  0.01528518,
          0.00518012, -0.02204286],
        [ 0.01548724,  0.02079786,  0.0313834 , ..., -0.02326493,
         -0.00597023,  0.03959525],
        ...,
        [-0.00377882, -0.01390042,  0.00276034, ...,  0.04459765,
         -0.0454565 ,  0.03515568],
        [-0.00377882, -0.01390042,  0.00276034, ...,  0.04459765,
         -0.0454565 ,  0.03515568],
        [-0.00377882, -0.01390042,  0.00276034, ...,  0.04459765,
         -0.0454565 ,  0.03515568]]], dtype=float32)>

<font color='red'>It's time to develop the model. In this case, I will be using a simple model for training.</font>

In [190]:
inputs = tf.keras.layers.Input(shape=(1,), dtype=tf.string)
x = vectorize(inputs)
x = embedding(x)
x = tf.keras.layers.Conv1D(filters=256, kernel_size=2, activation="relu", name="first_conf")(x)
x = tf.keras.layers.Conv1D(filters=256, kernel_size=3, activation="relu", name="second_conf")(x)
x = tf.keras.layers.Conv1D(filters=256, kernel_size=3, padding="valid", activation="relu", name="third_conv")(x)
x = tf.keras.layers.GlobalAveragePooling1D(name="g_pool")(x)
x = tf.keras.layers.Dense(128, activation="relu", name="dense_bro")(x)
outputs = tf.keras.layers.Dense(len(set(y_train_raw)), activation="softmax", name="final_dense")(x)
model_text = tf.keras.Model(inputs, outputs, name="model_text")
model_text.summary()

Model: "model_text"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_27 (InputLayer)       [(None, 1)]               0         
                                                                 
 text_vectorization_7 (TextV  (None, 314)              0         
 ectorization)                                                   
                                                                 
 embedding_3 (Embedding)     (None, 314, 256)          83501568  
                                                                 
 first_conf (Conv1D)         (None, 313, 256)          131328    
                                                                 
 second_conf (Conv1D)        (None, 311, 256)          196864    
                                                                 
 third_conv (Conv1D)         (None, 309, 256)          196864    
                                                        

<font color='red'>Define callbacks for updating the learning rate, early stopping if the model does not show improvement, and saving the model if any improvement occurs.</font>

In [215]:
lr_callback = tf.keras.callbacks.ReduceLROnPlateau(monitor="loss", # quantity to be monitored.
                                                   factor=0.2, # factor by which the learning rate will be reduced. new_lr = lr * factor.
                                                   patience=5, # number of epochs with no improvement after which learning rate will be reduced.
                                                   min_lr=1e-7) # lower bound on the learning rate.

In [216]:
es_callback = tf.keras.callbacks.EarlyStopping(monitor="loss",
                                               patience=5, # Number of epochs with no improvement after which training will be stopped.
                                               start_from_epoch=5,
                                               mode="min") # training will stop when the quantity monitored has stopped decreasing

In [217]:
save_callback = tf.keras.callbacks.ModelCheckpoint(filepath="checkpoint/model-1/model_text.hdf5",
                                                   monitor="val_loss",
                                                   save_best_only=True,
                                                   save_weights_only=False,
                                                   save_format='tf')

<font color='red'>Define the metrics to be displayed during the training process.</font>

In [207]:
metrics = [tf.keras.metrics.SparseCategoricalAccuracy(name='accuracy')]

<font color='red'>Now let's proceed with training the model.</font>

In [227]:
BATCH_SIZE = 32

train = train.batch(BATCH_SIZE).cache()
test = test.batch(BATCH_SIZE).cache()
val = val.batch(BATCH_SIZE).cache()

In [229]:
model_text.compile(loss="sparse_categorical_crossentropy",
                   optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
                   metrics=metrics)

In [228]:
history_text = model_text.fit(train,
                              epochs=200,
                              validation_data=val,
                              validation_steps=len(val),
                              callbacks=[lr_callback, es_callback, save_callback])

Epoch 1/200


2023-04-06 08:45:22.199342: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype int64 and shape [1000]
	 [[{{node Placeholder/_1}}]]
2023-04-06 08:45:22.199855: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype int64 and shape [1000]
	 [[{{node Placeholder/_1}}]]


ValueError: in user code:

    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1268, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1249, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1050, in train_step
        y_pred = self(x, training=True)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/text_vectorization.py", line 573, in _preprocess
        raise ValueError(

    ValueError: Exception encountered when calling layer 'text_vectorization_7' (type TextVectorization).
    
    When using `TextVectorization` to tokenize strings, the input rank must be 1 or the last shape dimension must be 1. Received: inputs.shape=(None, None) with rank=2
    
    Call arguments received by layer 'text_vectorization_7' (type TextVectorization):
      • inputs=tf.Tensor(shape=(None, None), dtype=string)


In [221]:
for x in val:
    print(x)
    break

(<tf.Tensor: shape=(32,), dtype=string, numpy=
array([b'Adrenergic activation is thought to be an important determinant of outcome in subjects with chronic heart failure ( CHF ) , but baseline or serial changes in adrenergic activity have not been previously investigated in a large patient sample treated with a powerful antiadrenergic agent .',
       b'Systemic venous norepinephrine was measured at baseline , @ months , and @ months in the beta-Blocker Evaluation of Survival Trial ( BEST ) , which compared placebo treatment with the beta-blocker/sympatholytic agent bucindolol .',
       b'Baseline norepinephrine level was associated with a progressive increase in rates of death or death plus CHF hospitalization that was independent of treatment group .',
       b'On multivariate analysis , baseline norepinephrine was also a highly significant ( P < @ ) independent predictor of death .',
       b'In contrast , the relation of the change in norepinephrine at @ months to subsequent clini

2023-04-06 08:43:25.016013: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype int64 and shape [28932]
	 [[{{node Placeholder/_1}}]]
2023-04-06 08:43:25.024773: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
